/*
Copyright (c) 2008,2009, CodeSLoop Team

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials_ provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#include "codesloop/rpc/stub_base.hh"
#include "codesloop/common/common.h"
#include "codesloop/common/ustr.hh"
#include "codesloop/rpc/csrparser.hh"
#include "codesloop/common/logger.hh"

#include <iostream>
#include <fstream>

using csl::common::ustr;
using std::endl;

/**
  @file rpc/src/stub_base.cc
  @brief implementation of codesloop interface descriptor
 */

namespace csl
{
  namespace rpc
  {
    stub_base::stub_base(const iface * i) : csl::common::obj()
    {
      ENTER_FUNCTION();

      ifc_    = i;
      ifname_ = ifc_->get_name().c_str();
      ls_     = "";


      LEAVE_FUNCTION();
    }

    stub_base::~stub_base()
    {
      ENTER_FUNCTION();

      if ( output_.is_open() )
        output_.close();

      LEAVE_FUNCTION();
    }

    void stub_base::open_file(const char * filename)
    {
      ENTER_FUNCTION();

      if ( output_.is_open() ) {
        output_.close();
        ls_ = "";
      }

      output_.open( filename, std::ios_base::out );

      output_ 
        << "/* THIS FILE IS AUTOMATICALLY GENERATED BY CSRGEN */" << endl          
        << "/*          DO NOT EDIT IT MANUALLY               */" << endl
        << endl;

      LEAVE_FUNCTION();
    }

    void stub_base::generate_ns_open()
    {
      ENTER_FUNCTION();
      char * nspc = strdup( ifc_->get_namespc().c_str());
      char * pch = strtok(nspc ,":");

      while (pch != NULL)
      {
        output_ 
          << ls_ << "namespace " << pch << endl
          << ls_ << "{" 
          << endl
        ;

        ls_ += "  ";

        pch = strtok (NULL, ":");
      }

      output_ << endl;

      if (nspc != NULL)
        free(nspc);

      LEAVE_FUNCTION();
    }

    void stub_base::generate_ns_close()
    {
      ENTER_FUNCTION();

      for ( size_t i = ls_.size() ; i > 0 ; i -= 2 )
      {
        output_ 
          << ls_.substr(0,i-2) 
          << "} /* namespace */"
          << endl
        ;
      }

      ls_ = "";
      LEAVE_FUNCTION();
    }


    void stub_base::generate_func_params(
        std::string function, 
        stub_kind kind,
        bool is_async)
    {   
      ENTER_FUNCTION();

      /*---------------------------------------------------------\
      |  Generate function specs                                 |
      \---------------------------------------------------------*/
      iface::function_iterator func_it = ifc_->get_functions()->begin();
      iface::func::param_iterator param_it;

      for ( ; func_it != ifc_->get_functions()->end(); func_it++ )
      {
        if ( (*func_it).name != function )
          continue;

        param_it = (*func_it).params.begin();

        if ( is_async == true )
          output_ << ls_ << "\t/* inout */\tcsl::rpc::handle &\t__handle," << endl;

        if ( kind == STUB_SERVER )
          output_ << ls_ << "\t/* input */\tconst csl::rpc::client_info &\tci," << endl;

        // parameters
        while( param_it != (*func_it).params.end() ) 
        {
          if( (*param_it).kind==MD_EXCEPTION) 
          {
            output_
              << ls_ << "\t"
              << "/* throws "
              << (*param_it).type << " */" 
              ;

          } else { 
            output_ 
              << ls_ << "\t" 
              << "/* " 
              << param_kind_name[ (*param_it).kind ] << " */"
              << "\t"
              ;

            if ( (*param_it).kind==MD_INPUT )
              output_ << "const ";

            if (  (*param_it).is_array ) {
              output_ << "vec<" << (*param_it).type << ">";
            } else {
              output_ << (*param_it).type;
            }

            if ( (*param_it).kind==MD_INPUT )
              output_ << " &"; 
            else if ( (*param_it).kind==MD_OUTPUT && kind == STUB_CLIENT )
              output_ << " *";
            else if ( (*param_it).kind==MD_OUTPUT && kind == STUB_SERVER )
              output_ << " &";
            else if ( (*param_it).kind==MD_INOUT )
              output_ << " &";

            output_
              << "\t" << (*param_it).name  
              ;
          }

          param_it++;

          // TODO: now it works only, if exceptions are defined last
          if ( (*param_it).kind!=MD_EXCEPTION && param_it != (*func_it).params.end() )
            output_ << ",";
          output_ << endl;
        }

        output_ << ls_ << ")";

      }
      
      LEAVE_FUNCTION();
    }

    void stub_base::add_internal_functions()
    {
      ENTER_FUNCTION();
      struct iface::func f;
      struct iface::param p = { "uint64_t", "client_time", MD_INOUT, false , 0 };

      // TODO: make an interface for adding functions in iface

      // internal function #1: ping
      f.disposable = false;
      f.name = "ping";
      std::vector<iface::func> * functions; 
      functions = const_cast<std::vector<iface::func> *>(ifc_->get_functions());
      functions->push_back(f);
      // parameters
      (*functions)[functions->size()-1].params.push_back(p);
      p.name = "server_time";
      p.kind = MD_OUTPUT;
      (*functions)[functions->size()-1].params.push_back(p);

      LEAVE_FUNCTION();
    }
  }
};

/* EOF */
