/*
Copyright (c) 2008,2009, David Beck, Tamas Foldi

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#include "stub_header.hh"
#include "common.h"
#include "ustr.hh"
#include "csrparser.hh"

#include <iostream>
#include <fstream>

using csl::common::ustr;
using std::endl;

/**
  @file csl_rpc/src/stub_header.cc
  @brief implementation of codesloop interface descriptor
 */

namespace csl
{
  namespace rpc
  {
    void stub_header::generate(const iface * ifc) 
    {   
      std::string ls; 
      ustr ifname( ifc->get_name().c_str() );
      std::fstream output( (ifname+".hh").c_str(), std::ios_base::out );

      output 
        << "/* THIS FILE IS AUTOMATICALLY GENERATED BY CSRGEN */" << endl          
        << "/*          DO NOT EDIT IT MANUALLY               */" << endl
        << endl
        << "#ifndef __csl_interface_" << ifc->get_name().c_str() << endl
        << "#define __csl_interface_" << ifc->get_name().c_str() << endl 
        << "#ifdef __cplusplus" << endl
        << endl
      ;

      /*---------------------------------------------------------\
      |  Generate includes                                       |
      \---------------------------------------------------------*/
      iface::include_iterator inc_it = ifc->get_includes()->begin() ;

      if ( ifc->get_includes()->size() != 0 )
        output << "/* User defined includes */" << endl;

      while ( inc_it != ifc->get_includes()->end() )
      {
        output << "#include " << *inc_it << endl; 
        inc_it++;
      }
      output << endl;

      // TODO: CSL transport and rpc includes comes here

      output 
        << "#define __if_" << ifname.c_str()  << "_ver\t" 
        << "\"" << ifc->get_version() << "\""
        << endl;
      output 
        << "#define __if_" << ifname.c_str()  << "_crc\t" 
        << ustr( ifc->to_string().c_str() ).crc64().value()
        << "LL"
        << endl << endl;
            
      /*---------------------------------------------------------\
      |  Generate namespace info                                 |
      \---------------------------------------------------------*/
      
      // TODO

      /*---------------------------------------------------------\
      |  Generate function specs                                 |
      \---------------------------------------------------------*/
      iface::function_iterator func_it = ifc->get_functions()->begin();
      iface::func::param_iterator param_it;
      int func_seq = 0;

      while ( func_it != ifc->get_functions()->end() )
      {
        param_it = (*func_it).params.begin();

        output 
          << ls << "#define __func_"  << ifname.c_str()  << "_"
          << (*func_it).name << "_id " << func_seq++ << endl;

        output << ls << "void " << (*func_it).name << " (" << endl;

        // fix parameter for
        output << ls << "\t/* inout */\tcsl::rpc::conn &\t__rpc_con," << endl;

        // parameters
        while( param_it != (*func_it).params.end() ) 
        {
          if( (*param_it).kind==MD_EXCEPTION) 
          {
            output
              << ls << "\t"
              << "/* throws "
              << (*param_it).type << " */" 
              ;

          } else { 
            output 
              << ls << "\t" 
              << "/* " 
              << param_kind_name[ (*param_it).kind ] << " */"
              << "\t"
              << (*param_it).type 
            ;

            if ( (*param_it).kind==MD_INPUT && (*param_it).is_array )
              output << " "; // space needed only, when an arry ptr is coming
            else if ( (*param_it).kind==MD_OUTPUT )
              output << " *";
            else if ( (*param_it).kind==MD_INOUT )
              output << " &";

            if ( (*param_it).is_array )
              output << "*";

            output
              << "\t" << (*param_it).name  
              ;
          }

          param_it++;
          
          // TODO: now it works only, if exceptions are defined last
          if ( (*param_it).kind!=MD_EXCEPTION && param_it != (*func_it).params.end() )
            output << ",";
          output << endl;
        }

        output << ls << ");" << endl << endl;
        func_it++;
      }
      output << endl;


      // TODO

      /*---------------------------------------------------------\
      |  Cleanup                                                 |
      \---------------------------------------------------------*/
      output
        << endl
        << "#ifndef /* __csl_interface_" << ifc->get_name().c_str() << "*/" 
        << endl
        << "#endif /* __cplusplus */" << endl
        << "/* EOF */" << endl
      ;

      output.close();
    }
  };
};

/* EOF */
